###
GET http://localhost:8000/api/users
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MzRmOTU1MGVhMWQyMjE5YjBjYTg0ZCIsImZpcnN0TmFtZSI6IkJhdEVyZGVuZSIsImxhc3ROYW1lIjoiR2Fuem9yaWciLCJVc2VybmFtZSI6IkdhbnpvIiwiZW1haWwiOiJiYXRlcmRlbmVnYW56b3JpZzk5QGdtYWlsLmNvbSIsImJpcnRoRGF0ZSI6IjIwMDQtMDctMjFUMDA6MDA6MDAuMDAwWiIsInBob25lTnVtYmVyIjo4OTAxODQxNywicm9sZSI6IkFkbWluIiwiYWRkcmVzcyI6IlVCIiwicGFzc3dvcmQiOiIkMmIkMTAkZFZYL1hESkNsQ2VtRnZqbkM0S3ZjT1VjVjhVTWk5RkwuVHhVNS5USEt1YU9JQWtnR2ZwUzIiLCJnZW5kZXIiOiJNYWxlIiwiZmF2SXRlbXMiOlsiaGkiXSwiX192IjowfSwiaWF0IjoxNjgyNDgzNDc1LCJleHAiOjE2ODI1Njk4NzV9.UxIa6hRwR3P4p92d9HY-2suvaCbHi-4sp3zUvNqMW4w

###
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "pageSize" : 1,
    "searchText" : "Ganzoo"
}
###
GET http://localhost:8000/api/user/6434f205c6a236e8814af1ed


###
PUT http://localhost:8000/api/user/64529ab1e4c101a725ebb373
Content-Type: application/json

{
    "password" : "123"
}


###
POST http://localhost:8000/api/user
Content-Type: application/json

{
   "firstName" : "BatErdene",
   "lastName" : "Ganzorig",
   "Username" : "Ganzo",
   "email" : "baterdeneganzorig99@gmail.com",
   "birthDate" : "2004-07-21",
   "phoneNumber" : 89018417,
   "role" : "Admin",
   "address" : "UB",
   "password" : "123",
   "gender" : "Male",
   "favItems" : ["hi"]

} 
###
DELETE http://localhost:8000/api/user/6434ed7e8b232f101bfbb4fa

###
POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "searchText" : "Ном"
}

###
GET http://localhost:8000/api/category

###
POST http://localhost:8000/api/category
Content-Type: application/json

{    
    "categoryName" : "Бусад"
}

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email" : "baterdeneganzorig99@gmail.com",
    "password" : "123"
}

###
GET http://localhost:8000/api/item
###
POST http://localhost:8000/api/items
Content-Type: application/json

{
    "pageSize" : 1,
    "searchText" : "bag"
}

###
GET http://localhost:8000/api/item

###
POST http://localhost:8000/api/item
Content-Type: application/json

{
  "itemName" : "Gun",
  "itemPhoto" : "hi",
  "categoryId" : "6434f24ea29bc8df661b4240",
  "phoneNumber" : 89018416,
  "rating" : 5,
  "rentalPrice" : 10000,
  "rentalStartDate" : "2023-04-25",
  "rentalEndDate" : "2023-05-01",
  "description" : "hello"

}

###
PUT http://localhost:8000/api/item/

###
DELETE http://localhost:8000/api/item/

###
GET http://localhost:8000/api/admin

###
GET http://localhost:8000/api/admin/

###
POST http://localhost:8000/api/admin
Content-Type: application/json

{
    "email" : "baterdeneganzorig959@gmail.com",
    "password" : "123"

}

###
PUT http://localhost:8000/api/admin/
Content-Type: application/json

{

}

###
DELETE http://localhost:8000/api/admin/643523c2f0fc3a71bfe463a5


### 
GET http://localhost:8000/api/employee

###
GET http://localhost:8000/api/employee/

###
POST http://localhost:8000/api/employee
Content-Type: application/json

{
   "firstName" : "Ganzorig",
   "lastName" : "Baterdene",
   "username" : "Ganzoo",
   "address" : "hi",
   "phoneNumber" : 89018416,
   "profilePic" : "hi"
}

###
PUT http://localhost:8000/api/employee
Content-Type: application/json

{

}

###
DELETE http://localhost:8000/api/employee/